# Generated by Django 3.2.5 on 2022-03-18 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of person', max_length=64)),
                ('email', models.EmailField(help_text='email address of creator', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='description of task', max_length=255)),
                ('weblink', models.URLField(help_text='a web site link')),
                ('creation_date', models.DateField(verbose_name='date created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.person')),
            ],
        ),
    ]
