# Generated by Django 3.2.5 on 2022-03-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.CharField(default='descr', help_text='description of task', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='a short name for the task', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='weblink',
            field=models.URLField(blank=True, help_text='a web site link', null=True),
        ),
    ]
