# Generated by Django 3.2.5 on 2022-03-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220321_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isdone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(help_text='description of task', max_length=255),
        ),
    ]
