# Generated by Django 3.2.5 on 2022-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220410_1637'),
    ]

    operations = [
        migrations.RenameField('task','creator','assignee'),

    ]
