# Generated by Django 3.2.5 on 2022-04-13 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(help_text='an english translation', max_length=50)),
                ('esp', models.CharField(help_text='a spanish translation', max_length=50)),
                ('pos', models.CharField(help_text='the part of speech for the word, e.g. noun, verb', max_length=20)),
                ('sub_date', models.DateField(auto_now_add=True, help_text='date submitted')),
                ('user', models.ForeignKey(help_text='user that entered this translation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
